service: webspark-crm-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    JWT_SECRET: "your-secret-key"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource: "*"

functions:
  api:
    handler: src/server.handler
    events:
      - http:
          path: users/signup
          method: post
          cors: true
      - http:
          path: users/login
          method: post
          cors: true
      - http:
          path: customers
          method: get
          cors: true
      - http:
          path: customers
          method: post
          cors: true
      - http:
          path: customers/{customerId}
          method: get
          cors: true
      - http:
          path: customers/{customerId}
          method: put
          cors: true
      - http:
          path: customers/{customerId}
          method: delete
          cors: true
      - http:
          path: customers/{customerId}/tasks
          method: put
          cors: true
      - http:
          path: users/{id}/profile-picture
          method: post
          cors: true
      - http:
          path: users/{id}
          method: get
          cors: true
      - http:
          path: customers/{customerId}/notes
          method: put
          cors: true
      - http:
          path: customers/{customerId}/users
          method: put
          cors: true

package:
  include:
    - node_modules/**