service: webspark-crm-api

package:
  excludeDevDependencies: false
  patterns:
    - 'node_modules/**'    # Ensure all node modules are included
    - '!node_modules/.bin/**'  # Exclude unnecessary binaries
    - 'server.js'
    - 'package.json'
    - 'package-lock.json'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  memorySize: 1024  # Increase if needed
  timeout: 10  # Increase timeout to prevent premature function failures
  environment:
    JWT_SECRET: "your-secret-key"
    AWS_REGION: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "*"  # Consider using a specific ARN instead of '*'

functions:
  api:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-offline  # Useful for local testing

custom:
  serverless-offline:
    httpPort: 3000
