service: webspark-crm-api
provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    JWT_SECRET: "your-secret-key"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "*"

functions:
  api:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
