service: webspark-crm-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    JWT_SECRET: "your-secret-key"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "*"

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: signup
          method: post
      - http:
          path: login
          method: post
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any

package:
  exclude:
    - node_modules/**
  include:
    - node_modules/express/**
    - node_modules/serverless-http/**
    - node_modules/body-parser/**
    - node_modules/aws-sdk/**
    - node_modules/bcryptjs/**
    - node_modules/jsonwebtoken/**
    - node_modules/uuid/**
