name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Change Directory to Project Folder
        run: cd webspark-crm

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure the Node.js version matches your local setup

      - name: Install Dependencies
        run: yarn install  # Or `npm install` if you use npm

      - name: Build Vue App
        run: yarn build  # Or `npm run build` if you use npm

      - name: Install AWS CLI
        run: sudo apt-get -y install awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Change if your region differs

      - name: Sync Files to S3
        run: aws s3 sync ./dist s3://webspark-crm --delete
