name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Matches your local Node.js version

      - name: Install Dependencies
        working-directory: webspark-crm  # Navigate to the project directory
        run: yarn install

      - name: Build Vue App
        working-directory: webspark-crm  # Navigate to the project directory
        run: yarn build

      - name: Install AWS CLI
        run: sudo apt-get -y install awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Change if your region differs

      - name: Sync Files to S3
        working-directory: webspark-crm  # Make sure we’re in the correct folder
        run: aws s3 sync ./dist s3://webspark-crm --delete
