name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: frontend
        run: yarn install

      - name: Build Vue App
        working-directory: frontend
        env:
          VUE_APP_AWS_REGION: ${{ secrets.VUE_APP_AWS_REGION }}
          VUE_APP_AWS_ACCESS_KEY_ID: ${{ secrets.VUE_APP_AWS_ACCESS_KEY_ID }}
          VUE_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.VUE_APP_AWS_SECRET_ACCESS_KEY }}
        run: yarn build

      - name: Install AWS CLI
        run: |
          rm -rf aws  # Remove existing AWS CLI installation folder if it exists
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip  # Overwrite any existing files without asking
          sudo ./aws/install --update

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.VUE_APP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VUE_APP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.VUE_APP_AWS_REGION }}

      - name: Sync Files to S3
        working-directory: frontend
        run: aws s3 sync ./dist s3://webspark-crm-2 --delete
